//THIS SCRIPT REQUIRES ACCOUNTADMIN ROLE IN ORDER TO CREATE SHARE AND READ FROM "SNOWFLAKE" INTERNAL DATABASE
USE role ACCOUNTADMIN;

-----------------------------------------------------------------------------------------------------------------------------
-- 	"SHARE_USAGE" DATABASE IS A COPY OF SELECTED TABLES FROM SNOWFLAKE DATABASE
-- The following script creates a new database, copy some of the ACCOUNT_USAGE tables
-- and create a SNOWSHARE with SNOWLY - NO DATA IS SHARED BUT STATISTICS TABLES
-- please create the database using the script, then run the procedure to load data
-- and at the end share it using snowshare. You can review the database data before sharing it.
-----------------------------------------------------------------------------------------------------------------------------
/*
THIS ARE THE TABLES THAT WILL BE SHARED:
ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY - Storage history by database to analyze the usage of the fail safe
ACCOUNT_USAGE.QUERY_HISTORY - Queries to calculate the actual usage. Please notice, the first 100 chars of the queries
                                is copied "LEFT(QUERY_TEXT,100) QUERY_TEXT", if you find it sensitive you can change the procedure
ACCOUNT_USAGE.STORAGE_USAGE - Storage history
ACCOUNT_USAGE.TABLE_STORAGE_METRICS - Current Storage by table
ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY - WH Credits by warehouse & hour
ACCOUNT_USAGE.PIPE_USAGE_HISTORY - PIPE Credits by warehouse & hour
ACCOUNT_USAGE.WAREHOUSES - List of all warehouses ("SHOW WAREHOUSES")
ACCOUNT_USAGE.LOGIN_HISTORY - Login history to add the client type to the queries
ACCOUNT_USAGE.CLOUD_SERVICES_WO_WAREHOUSE_SIZE - Aggregation on the "QUERY_HISTORY" without warehouses (WAREHOUSE_SIZE is null)
*/

Create database SHARE_USAGE ;
Use database SHARE_USAGE;
Create Schema ACCOUNT_USAGE;
USE Schema ACCOUNT_USAGE;



CREATE OR REPLACE PROCEDURE SHARE_USAGE.ACCOUNT_USAGE.SP_ACCOUNT_USAGE_DATA(LOAD_METHOD STRING)
RETURNS STRING
LANGUAGE javascript
strict
EXECUTE AS owner
AS

$$

// SET VARIABLES
var full_script = `Create  table if not exists ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY as
Select START_TIME,END_TIME,WAREHOUSE_ID,WAREHOUSE_NAME,CREDITS_USED, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."WAREHOUSE_METERING_HISTORY"
Where  1=0;

Insert into ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY (START_TIME,END_TIME,WAREHOUSE_ID,WAREHOUSE_NAME,CREDITS_USED,CREATED)
Select START_TIME,END_TIME,WAREHOUSE_ID,WAREHOUSE_NAME,CREDITS_USED, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."WAREHOUSE_METERING_HISTORY"
Where  START_TIME > IFNULL((Select Max(START_TIME) From ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY),'2000-01-01');


Create table if not exists ACCOUNT_USAGE.QUERY_HISTORY as
Select QUERY_ID ,LEFT(QUERY_TEXT,100) QUERY_TEXT ,DATABASE_ID ,DATABASE_NAME ,SCHEMA_ID ,SCHEMA_NAME ,QUERY_TYPE ,SESSION_ID ,USER_NAME ,ROLE_NAME ,
        WAREHOUSE_ID ,WAREHOUSE_NAME ,WAREHOUSE_SIZE ,WAREHOUSE_TYPE ,CLUSTER_NUMBER ,QUERY_TAG ,EXECUTION_STATUS ,ERROR_CODE ,ERROR_MESSAGE ,
        START_TIME ,END_TIME ,TOTAL_ELAPSED_TIME ,BYTES_SCANNED ,ROWS_PRODUCED ,COMPILATION_TIME ,EXECUTION_TIME ,QUEUED_PROVISIONING_TIME ,
        QUEUED_REPAIR_TIME ,QUEUED_OVERLOAD_TIME ,TRANSACTION_BLOCKED_TIME ,OUTBOUND_DATA_TRANSFER_CLOUD ,OUTBOUND_DATA_TRANSFER_REGION ,
        OUTBOUND_DATA_TRANSFER_BYTES ,INBOUND_DATA_TRANSFER_CLOUD ,INBOUND_DATA_TRANSFER_REGION ,INBOUND_DATA_TRANSFER_BYTES,
       LIST_EXTERNAL_FILES_TIME,CREDITS_USED_CLOUD_SERVICES
        , current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."QUERY_HISTORY"
Where 1=0;

Insert Into ACCOUNT_USAGE.QUERY_HISTORY (QUERY_ID ,QUERY_TEXT ,DATABASE_ID ,DATABASE_NAME ,SCHEMA_ID ,SCHEMA_NAME ,QUERY_TYPE ,SESSION_ID ,USER_NAME ,ROLE_NAME ,
        WAREHOUSE_ID ,WAREHOUSE_NAME ,WAREHOUSE_SIZE ,WAREHOUSE_TYPE ,CLUSTER_NUMBER ,QUERY_TAG ,EXECUTION_STATUS ,ERROR_CODE ,ERROR_MESSAGE ,
        START_TIME ,END_TIME ,TOTAL_ELAPSED_TIME ,BYTES_SCANNED ,ROWS_PRODUCED ,COMPILATION_TIME ,EXECUTION_TIME ,QUEUED_PROVISIONING_TIME ,
        QUEUED_REPAIR_TIME ,QUEUED_OVERLOAD_TIME ,TRANSACTION_BLOCKED_TIME ,OUTBOUND_DATA_TRANSFER_CLOUD ,OUTBOUND_DATA_TRANSFER_REGION ,
        OUTBOUND_DATA_TRANSFER_BYTES ,INBOUND_DATA_TRANSFER_CLOUD ,INBOUND_DATA_TRANSFER_REGION ,INBOUND_DATA_TRANSFER_BYTES,
       LIST_EXTERNAL_FILES_TIME,CREDITS_USED_CLOUD_SERVICES, CREATED)
Select QUERY_ID ,LEFT(QUERY_TEXT,100) QUERY_TEXT ,DATABASE_ID ,DATABASE_NAME ,SCHEMA_ID ,SCHEMA_NAME ,QUERY_TYPE ,SESSION_ID ,USER_NAME ,ROLE_NAME ,
        WAREHOUSE_ID ,WAREHOUSE_NAME ,WAREHOUSE_SIZE ,WAREHOUSE_TYPE ,CLUSTER_NUMBER ,QUERY_TAG ,EXECUTION_STATUS ,ERROR_CODE ,ERROR_MESSAGE ,
        START_TIME ,END_TIME ,TOTAL_ELAPSED_TIME ,BYTES_SCANNED ,ROWS_PRODUCED ,COMPILATION_TIME ,EXECUTION_TIME ,QUEUED_PROVISIONING_TIME ,
        QUEUED_REPAIR_TIME ,QUEUED_OVERLOAD_TIME ,TRANSACTION_BLOCKED_TIME ,OUTBOUND_DATA_TRANSFER_CLOUD ,OUTBOUND_DATA_TRANSFER_REGION ,
        OUTBOUND_DATA_TRANSFER_BYTES ,INBOUND_DATA_TRANSFER_CLOUD ,INBOUND_DATA_TRANSFER_REGION ,INBOUND_DATA_TRANSFER_BYTES,
       LIST_EXTERNAL_FILES_TIME,CREDITS_USED_CLOUD_SERVICES, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."QUERY_HISTORY"
Where WAREHOUSE_SIZE is not null and START_TIME > IFNULL((Select Max(START_TIME) From ACCOUNT_USAGE.QUERY_HISTORY),'2000-01-01');

Create table if not exists  ACCOUNT_USAGE.CLOUD_SERVICES_WO_WAREHOUSE_SIZE as
Select  LEFT(START_TIME , 13) HOUR_ID ,DATABASE_ID ,DATABASE_NAME ,SCHEMA_ID ,SCHEMA_NAME ,QUERY_TYPE  ,USER_NAME ,ROLE_NAME ,
        WAREHOUSE_ID ,WAREHOUSE_NAME ,WAREHOUSE_SIZE ,WAREHOUSE_TYPE ,CLUSTER_NUMBER ,QUERY_TAG ,EXECUTION_STATUS ,ERROR_CODE  ,
        SUM(TOTAL_ELAPSED_TIME) SUM_TOTAL_ELAPSED_TIME ,SUM(CREDITS_USED_CLOUD_SERVICES) SUM_CREDITS_USED_CLOUD_SERVICES, COUNT(*) NUM_QUERIES
       ,MAX(ERROR_MESSAGE) ERROR_MESSAGE
       , current_timestamp()  CREATED, MAX(START_TIME) MAX_START_TIME
From "SNOWFLAKE"."ACCOUNT_USAGE"."QUERY_HISTORY"
Where WAREHOUSE_SIZE is null  and 1=0
Group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16;

Insert into ACCOUNT_USAGE.CLOUD_SERVICES_WO_WAREHOUSE_SIZE (HOUR_ID ,DATABASE_ID ,DATABASE_NAME ,SCHEMA_ID ,SCHEMA_NAME ,QUERY_TYPE  ,USER_NAME ,ROLE_NAME ,
        WAREHOUSE_ID ,WAREHOUSE_NAME ,WAREHOUSE_SIZE ,WAREHOUSE_TYPE ,CLUSTER_NUMBER ,QUERY_TAG ,EXECUTION_STATUS ,ERROR_CODE  ,SUM_TOTAL_ELAPSED_TIME ,
        SUM_CREDITS_USED_CLOUD_SERVICES, NUM_QUERIES,ERROR_MESSAGE, CREATED, MAX_START_TIME)
Select  LEFT(START_TIME , 13) HOUR_ID ,DATABASE_ID ,DATABASE_NAME ,SCHEMA_ID ,SCHEMA_NAME ,QUERY_TYPE  ,USER_NAME ,ROLE_NAME ,
        WAREHOUSE_ID ,WAREHOUSE_NAME ,WAREHOUSE_SIZE ,WAREHOUSE_TYPE ,CLUSTER_NUMBER ,QUERY_TAG ,EXECUTION_STATUS ,ERROR_CODE  ,
        SUM(TOTAL_ELAPSED_TIME) SUM_TOTAL_ELAPSED_TIME ,SUM(CREDITS_USED_CLOUD_SERVICES) SUM_CREDITS_USED_CLOUD_SERVICES, COUNT(*) NUM_QUERIES
       ,MAX(ERROR_MESSAGE) ERROR_MESSAGE
       , current_timestamp()  CREATED, MAX(START_TIME) MAX_START_TIME
From "SNOWFLAKE"."ACCOUNT_USAGE"."QUERY_HISTORY"
Where WAREHOUSE_SIZE is null
    and START_TIME > IFNULL((Select Max(MAX_START_TIME) From ACCOUNT_USAGE.CLOUD_SERVICES_WO_WAREHOUSE_SIZE),'2000-01-01')
Group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16;

Create table if not exists  ACCOUNT_USAGE.STORAGE_USAGE as
Select USAGE_DATE,STORAGE_BYTES,STAGE_BYTES,FAILSAFE_BYTES, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."STORAGE_USAGE"
Where 1=0;

Insert Into ACCOUNT_USAGE.STORAGE_USAGE (USAGE_DATE,STORAGE_BYTES,STAGE_BYTES,FAILSAFE_BYTES,CREATED)
Select USAGE_DATE,STORAGE_BYTES,STAGE_BYTES,FAILSAFE_BYTES, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."STORAGE_USAGE"
Where USAGE_DATE > IFNULL((Select Max(USAGE_DATE) From STORAGE_USAGE),'2000-01-01');

Create table if not exists  ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY as
Select USAGE_DATE,DATABASE_ID,DATABASE_NAME,DELETED,AVERAGE_DATABASE_BYTES,AVERAGE_FAILSAFE_BYTES , current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."DATABASE_STORAGE_USAGE_HISTORY"
Where 1=0;

Insert Into ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY (USAGE_DATE,DATABASE_ID,DATABASE_NAME,DELETED,AVERAGE_DATABASE_BYTES,AVERAGE_FAILSAFE_BYTES ,CREATED)
Select USAGE_DATE,DATABASE_ID,DATABASE_NAME,DELETED,AVERAGE_DATABASE_BYTES,AVERAGE_FAILSAFE_BYTES , current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."DATABASE_STORAGE_USAGE_HISTORY"
Where USAGE_DATE > IFNULL((Select Max(USAGE_DATE) From ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY),'2000-01-01');

Create table if not exists ACCOUNT_USAGE.TABLE_STORAGE_METRICS as
Select ID,TABLE_NAME,TABLE_SCHEMA_ID,TABLE_SCHEMA,TABLE_CATALOG_ID,TABLE_CATALOG,CLONE_GROUP_ID, IS_TRANSIENT,ACTIVE_BYTES,TIME_TRAVEL_BYTES,FAILSAFE_BYTES,RETAINED_FOR_CLONE_BYTES,TABLE_CREATED,TABLE_DROPPED,TABLE_ENTERED_FAILSAFE,SCHEMA_CREATED,SCHEMA_DROPPED,CATALOG_CREATED,CATALOG_DROPPED,COMMENT, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."TABLE_STORAGE_METRICS"
Where 1=0;

Insert into ACCOUNT_USAGE.TABLE_STORAGE_METRICS (ID,TABLE_NAME,TABLE_SCHEMA_ID,TABLE_SCHEMA,TABLE_CATALOG_ID,TABLE_CATALOG,CLONE_GROUP_ID, IS_TRANSIENT,ACTIVE_BYTES,TIME_TRAVEL_BYTES,FAILSAFE_BYTES,RETAINED_FOR_CLONE_BYTES,TABLE_CREATED,TABLE_DROPPED,TABLE_ENTERED_FAILSAFE,SCHEMA_CREATED,SCHEMA_DROPPED,CATALOG_CREATED,CATALOG_DROPPED,COMMENT,CREATED)
Select ID,TABLE_NAME,TABLE_SCHEMA_ID,TABLE_SCHEMA,TABLE_CATALOG_ID,TABLE_CATALOG,CLONE_GROUP_ID, IS_TRANSIENT,ACTIVE_BYTES,TIME_TRAVEL_BYTES,FAILSAFE_BYTES,RETAINED_FOR_CLONE_BYTES,TABLE_CREATED,TABLE_DROPPED,TABLE_ENTERED_FAILSAFE,SCHEMA_CREATED,SCHEMA_DROPPED,CATALOG_CREATED,CATALOG_DROPPED,COMMENT, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."TABLE_STORAGE_METRICS"
Where TO_DATE(current_timestamp()) not in (SELECT TO_DATE(MAX(CREATED)) FROM ACCOUNT_USAGE.TABLE_STORAGE_METRICS);

Create table if not exists ACCOUNT_USAGE.PIPE_USAGE_HISTORY as
Select PIPE_ID,PIPE_NAME,START_TIME,END_TIME,CREDITS_USED,BYTES_INSERTED,FILES_INSERTED, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."PIPE_USAGE_HISTORY"
Where 1=0;

Insert into  ACCOUNT_USAGE.PIPE_USAGE_HISTORY (PIPE_ID,PIPE_NAME,START_TIME,END_TIME,CREDITS_USED,BYTES_INSERTED,FILES_INSERTED,CREATED)
Select PIPE_ID,PIPE_NAME,START_TIME,END_TIME,CREDITS_USED,BYTES_INSERTED,FILES_INSERTED, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."PIPE_USAGE_HISTORY"
Where START_TIME > IFNULL((Select Max(START_TIME) From ACCOUNT_USAGE.PIPE_USAGE_HISTORY),'2000-01-01');

Create table if not exists ACCOUNT_USAGE.LOGIN_HISTORY as
Select EVENT_ID,EVENT_TIMESTAMP,EVENT_TYPE,USER_NAME,CLIENT_IP,REPORTED_CLIENT_TYPE,REPORTED_CLIENT_VERSION,FIRST_AUTHENTICATION_FACTOR,SECOND_AUTHENTICATION_FACTOR,IS_SUCCESS,ERROR_CODE,ERROR_MESSAGE,RELATED_EVENT_ID, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."LOGIN_HISTORY"
Where 1=0;

Insert into  ACCOUNT_USAGE.LOGIN_HISTORY (EVENT_ID,EVENT_TIMESTAMP,EVENT_TYPE,USER_NAME,CLIENT_IP,REPORTED_CLIENT_TYPE,REPORTED_CLIENT_VERSION,FIRST_AUTHENTICATION_FACTOR,SECOND_AUTHENTICATION_FACTOR,IS_SUCCESS,ERROR_CODE,ERROR_MESSAGE,RELATED_EVENT_ID,CREATED)
Select EVENT_ID,EVENT_TIMESTAMP,EVENT_TYPE,USER_NAME,CLIENT_IP,REPORTED_CLIENT_TYPE,REPORTED_CLIENT_VERSION,FIRST_AUTHENTICATION_FACTOR,SECOND_AUTHENTICATION_FACTOR,IS_SUCCESS,ERROR_CODE,ERROR_MESSAGE,RELATED_EVENT_ID, current_timestamp() CREATED
From "SNOWFLAKE"."ACCOUNT_USAGE"."LOGIN_HISTORY"
Where EVENT_TIMESTAMP > IFNULL((Select Max(EVENT_TIMESTAMP) From ACCOUNT_USAGE.LOGIN_HISTORY),'2000-01-01');

show warehouses;
Create table if not exists ACCOUNT_USAGE.WAREHOUSES as
Select "name" NAME,"state" STATE,"type" TYPE,"size" SIZE,"queued" QUEUED,"is_default" IS_DEFAULT,"is_current" IS_CURRENT,"auto_suspend" AUTO_SUSPEND,"auto_resume" AUTO_RESUME,"available" AVAILABLE,"provisioning" PROVISIONING,"quiescing" QUIESCING
,"other" OTHER,"created_on" CREATED_ON,"resumed_on" RESUMED_ON,"updated_on" UPDATED_ON,"owner" OWNER,"comment" COMMENT,"resource_monitor" RESOURCE_MONITOR,"actives" ACTIVITIES,"pendings" PENDINGS,"failed" FAILED,"suspended" SUSPENDED,"uuid" UUID, current_timestamp() CREATED
From TABLE(RESULT_SCAN ( LAST_QUERY_ID()  ))
WHERE 1=0;

show warehouses;
insert into ACCOUNT_USAGE.WAREHOUSES(NAME,STATE,TYPE,SIZE,QUEUED,IS_DEFAULT,IS_CURRENT,AUTO_SUSPEND,AUTO_RESUME,AVAILABLE,PROVISIONING,QUIESCING
,OTHER,CREATED_ON,RESUMED_ON,UPDATED_ON,OWNER,COMMENT,RESOURCE_MONITOR,ACTIVITIES,PENDINGS,FAILED,SUSPENDED,UUID,CREATED)
Select "name" NAME,"state" STATE,"type" TYPE,"size" SIZE,"queued" QUEUED,"is_default" IS_DEFAULT,"is_current" IS_CURRENT,"auto_suspend" AUTO_SUSPEND,"auto_resume" AUTO_RESUME,"available" AVAILABLE,"provisioning" PROVISIONING,"quiescing" QUIESCING
,"other" OTHER,"created_on" CREATED_ON,"resumed_on" RESUMED_ON,"updated_on" UPDATED_ON,"owner" OWNER,"comment" COMMENT,"resource_monitor" RESOURCE_MONITOR,"actives" ACTIVITIES,"pendings" PENDINGS,"failed" FAILED,"suspended" SUSPENDED,"uuid" UUID, current_timestamp() CREATED
From TABLE(RESULT_SCAN ( LAST_QUERY_ID()  ));
`
var message='';
try
{
for (j = 0; j < full_script.split(';').length; j++){

    curr_sql=full_script.split(';')[j];

    if(curr_sql && curr_sql.length>10){
        if($loading_method='FULL'){
        curr_sql = curr_sql.replace('table if not exists',' or replace table ')
        }
        var snowflake_statement = snowflake.createStatement( {sqlText: curr_sql});
        var result = snowflake_statement.execute();
        message=message+'|'+curr_sql;
    }
}
return 'Success'

    }
catch (err)  {

	var failure_msg = "Failed: " + err
    return failure_msg

	}

$$;



set add_comment= CONCAT(current_account(),' | ',  current_region());

CREATE SHARE SHARE_USAGE_SH COMMENT=$add_comment ;
grant usage on database  SHARE_USAGE  to share SHARE_USAGE_SH;
ALTER SHARE SHARE_USAGE_SH ADD ACCOUNTS = ch52627;

grant usage on schema SHARE_USAGE.ACCOUNT_USAGE to share SHARE_USAGE_SH;

grant select on all tables in schema SHARE_USAGE.ACCOUNT_USAGE to share SHARE_USAGE_SH;
GRANT USAGE ON SCHEMA SHARE_USAGE.ACCOUNT_USAGE TO SHARE SHARE_USAGE_SH;
GRANT SELECT ON VIEW SHARE_USAGE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY TO SHARE SHARE_USAGE_SH;
GRANT SELECT ON VIEW SHARE_USAGE.ACCOUNT_USAGE.QUERY_HISTORY TO SHARE SHARE_USAGE_SH;
GRANT SELECT ON VIEW SHARE_USAGE.ACCOUNT_USAGE.STORAGE_USAGE TO SHARE SHARE_USAGE_SH;
GRANT SELECT ON VIEW SHARE_USAGE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS TO SHARE SHARE_USAGE_SH;
GRANT SELECT ON VIEW SHARE_USAGE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY TO SHARE SHARE_USAGE_SH;
GRANT SELECT ON VIEW SHARE_USAGE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY TO SHARE SHARE_USAGE_SH;
GRANT SELECT ON VIEW SHARE_USAGE.ACCOUNT_USAGE.WAREHOUSES TO SHARE SHARE_USAGE_SH;
GRANT SELECT ON VIEW SHARE_USAGE.ACCOUNT_USAGE.LOGIN_HISTORY TO SHARE SHARE_USAGE_SH;
GRANT SELECT ON VIEW SHARE_USAGE.ACCOUNT_USAGE.CLOUD_SERVICES_WO_WAREHOUSE_SIZE TO SHARE SHARE_USAGE_SH;


  --CREATE TASK
  create or replace task SHARE_USAGE.ACCOUNT_USAGE.TASK_ACCOUNT_USAGE
  warehouse = SNOWLY
  schedule = 'using cron 0 4,12,20 * * * UTC'
    as
  call SHARE_USAGE.ACCOUNT_USAGE.SP_ACCOUNT_USAGE_DATA();


  call SHARE_USAGE.ACCOUNT_USAGE.SP_ACCOUNT_USAGE_DATA('FULL');

  --ACTIVATE TASK
  ALTER TASK SHARE_USAGE.ACCOUNT_USAGE.TASK_ACCOUNT_USAGE  RESUME;